### ISSUE TITLE
Unknown method: HEAD

### ISSUE THREAD

**Issue by abrighton** [guardrail-dev/sbt-guardrail#207]
I get the error "Unknown method: HEAD" when the OpenApi file (YAML or JSON) contains a "head" item. 
I am attempting to generate an Http4s server with the plugin:
  
   addSbtPlugin("dev.guardrail"    % "sbt-guardrail"       % "0.75.1")

If I comment out the "head" item, it works.

**Comment by abrighton** [comment]
I added https://github.com/guardrail-dev/guardrail/issues/1682, since that seems to be where the code is mising.

**Comment by blast-hardcheese** [comment]
Thank you for your contribution! Closing this out
